{% set version = "7.4.4" %}

package:
  name: grass-python2
  version: {{ version }}

source:
  - path: .

build:
  number: 1002
  skip_compile_pyc:
    - "*/*.py"

requirements:
  host:
    - python2
    # python2 pkg is not a run requiremnt, if a python2 (>=2.7.15) is found on PATH

test:
  requires:
    - python2

about:
  home: https://grass.osgeo.org
  license: PSF
  summary: Python 2 packages for GRASS 7
  description: Python 2 packages for GRASS 7. See recipe directory for package licenses.
  doc_url: https://grass.osgeo.org/grass74/source/REQUIREMENTS.html
  dev_url: https://grasswiki.osgeo.org/wiki/Compile_and_Install

extra:
  recipe-maintainers:
    - dakcarto
